version: '3.8'

services:
  app:
    build: .
    container_name: familiaMogi-app
    ports:
      - "8000:8000"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    restart: always
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    command: php artisan serve --host=0.0.0.0 --port=8000

  vite:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    command: bash -c "npm install && npm run watch"
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: familiaMogi
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
