version: '3.8'

services:
  app:
    build: .
    container_name: familiaMogi-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    restart: "no"
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
    ports:
      - "8000:80"   # Mapeando a porta 80 do Apache para 8000 da máquina
    command: bash -c "chown -R www-data:www-data storage bootstrap/cache && apache2-foreground"

  node:
    image: node:20
    container_name: familiaMogi-node
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    command: bash -c "npm install && npm run dev"
    depends_on:
      - app
    restart: "no"

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: familiaMogi
      MYSQL_USER: familiaMogi
      MYSQL_PASSWORD: rootpassword123
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
